"""add order_timeline timestamps

Revision ID: ad09e9164aca
Revises: 80700474ce05
Create Date: 2026-10-09 15:24:34.480478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad09e9164aca'
down_revision: Union[str, None] = '80700474ce05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_timeline', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_timeline', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_timeline', 'updated_at')
    op.drop_column('order_timeline', 'created_at')
    # ### end Alembic commands ###
